# Generated by Django 2.2.10 on 2020-04-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='description',
            field=models.TextField(default='gogu'),
            preserve_default=False,
        ),
    ]
