# Generated by Django 2.2.10 on 2020-03-25 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_adminblog_adminmobil_adminnewsletter_adminplati_adminposta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminnewsletter',
            old_name='user',
            new_name='admin_newsletter',
        ),
    ]
