# Generated by Django 2.2.10 on 2020-03-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200325_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'admin newsletter'), (2, 'admin blog'), (3, 'admin payment'), (4, 'admin phone'), (5, 'admin postal'), (6, 'regular user'), (0, 'administrator')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='users.UserRole'),
        ),
    ]
