# Generated by Django 2.2.10 on 2020-03-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200325_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmobil',
            name='user',
        ),
        migrations.RemoveField(
            model_name='adminnewsletter',
            name='admin_newsletter',
        ),
        migrations.RemoveField(
            model_name='adminplati',
            name='user',
        ),
        migrations.RemoveField(
            model_name='adminposta',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminBlog',
        ),
        migrations.DeleteModel(
            name='AdminMobil',
        ),
        migrations.DeleteModel(
            name='AdminNewsletter',
        ),
        migrations.DeleteModel(
            name='AdminPlati',
        ),
        migrations.DeleteModel(
            name='AdminPosta',
        ),
    ]
