# Generated by Django 2.2.10 on 2020-04-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200325_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin newsletter'), (2, 'admin blog'), (3, 'admin payment'), (4, 'admin phone'), (5, 'admin postal'), (6, 'regular user'), (0, 'administrator')], default=7, primary_key=True, serialize=False),
        ),
    ]
