# Generated by Django 2.2.10 on 2020-04-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200418_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='memeber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
