# Generated by Django 2.2.10 on 2020-04-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_memeber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='memeber',
            new_name='member',
        ),
    ]
