# Generated by Django 2.2.10 on 2020-04-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200419_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tos',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
