# Generated by Django 2.2.10 on 2020-04-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_tos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
    ]
