# Generated by Django 2.2.10 on 2020-04-11 12:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cookiepagetext',
            old_name='text',
            new_name='cookie_text',
        ),
        migrations.AddField(
            model_name='cookiepagetext',
            name='statut_text',
            field=ckeditor.fields.RichTextField(default='Hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cookiepagetext',
            name='tos_text',
            field=ckeditor.fields.RichTextField(default='Helo'),
            preserve_default=False,
        ),
    ]
