# Generated by Django 2.2.10 on 2020-04-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0003_auto_20200411_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookiepagetext',
            options={'verbose_name': 'Cookie', 'verbose_name_plural': 'Cookie-uri'},
        ),
        migrations.AlterModelOptions(
            name='statuspagetext',
            options={'verbose_name': 'Statut'},
        ),
        migrations.AlterModelOptions(
            name='tospagetext',
            options={'verbose_name': 'Termeni si conditii'},
        ),
        migrations.RenameField(
            model_name='statuspagetext',
            old_name='status_text',
            new_name='statut_text',
        ),
    ]
