# Generated by Django 2.2.10 on 2020-04-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookies', '0004_auto_20200411_1342'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusPageText',
            new_name='StatutPageText',
        ),
    ]
